import { Colors } from "../types/general";

export const colorData: Colors[] = [
  { name: "White", mainColor: "#FFFFFF", shades: [] },
  { name: "Black", mainColor: "#000000", shades: [] },
  {
    name: "Red",
    mainColor: "#FF0000",
    shades: ["#800000", "#B30000", "#E60000", "#FF1A1A", "#FF4D4D"],
  },
  {
    name: "Green",
    mainColor: "#00FF00",
    shades: ["#008000", "#00B300", "#00E600", "#1AFF1A", "#4DFF4D"],
  },
  {
    name: "Blue",
    mainColor: "#0000FF",
    shades: ["#000080", "#0000B3", "#0000E6", "#1A1AFF", "#4D4DFF"],
  },
  {
    name: "Brown",
    mainColor: "#964B00",
    shades: ["#4B2600", "#693500", "#874400", "#A15D1A", "#B6814D"],
  },
  {
    name: "Aquamarine",
    mainColor: "#7FFFD4",
    shades: ["#40806A", "#59B394", "#72E6BF", "#8CFFD8", "#A5FFE1"],
  },
  {
    name: "Lavender",
    mainColor: "#E6E6FA",
    shades: ["#73737D", "#A1A1AF", "#CFCFE1", "#E9E9FB", "#EEEEFC"],
  },
  {
    name: "Magenta",
    mainColor: "#FF00FF",
    shades: ["#800080", "#B300B3", "#E600E6", "#FF1AFF", "#FF4DFF"],
  },
  {
    name: "Maroon",
    mainColor: "#800000",
    shades: ["#400000", "#5A0000", "#730000", "#8D1A1A", "#A64D4D"],
  },
  {
    name: "Yellow",
    mainColor: "#FFFF00",
    shades: ["#808000", "#B3B300", "#E6E600", "#FFFF1A", "#FFFF4D"],
  },
  {
    name: "Pink",
    mainColor: "#FFC0CB",
    shades: ["#806066", "#B3868E", "#E6ADB7", "#FFC6D0", "#FFD3DB"],
  },
  {
    name: "Coral",
    mainColor: "#FF7F50",
    shades: ["#804028", "#B35938", "#E67248", "#FF8C62", "#FFA585"],
  },
  {
    name: "Beige",
    mainColor: "#F5F5DC",
    shades: ["#7B7B6E", "#ACAC9A", "#DDDDC6", "#F6F6E0", "#F8F8E7"],
  },
  {
    name: "Gold",
    mainColor: "#FFD700",
    shades: ["#806C00", "#B39700", "#E6C200", "#FFDB1A", "#FFE34D"],
  },
  {
    name: "Violet",
    mainColor: "#8F00FF",
    shades: ["#480080", "#6400B3", "#8100E6", "#9A1AFF", "#B14DFF"],
  },
  {
    name: "Orange",
    mainColor: "#FFA500",
    shades: ["#805300", "#B37300", "#E69500", "#FFAE1A", "#FFC04D"],
  },
  {
    name: "Purple",
    mainColor: "#800080",
    shades: ["#400040", "#5A005A", "#730073", "#8D1A8D", "#A64DA6"],
  },
  {
    name: "Gray",
    mainColor: "#808080",
    shades: ["#404040", "#5A5A5A", "#737373", "#8D8D8D", "#A6A6A6"],
  },
  {
    name: "Indigo",
    mainColor: "#4B0082",
    shades: ["#260041", "#35005B", "#440075", "#5D1A8F", "#814DA8"],
  },
  {
    name: "Cyan",
    mainColor: "#00FFFF",
    shades: ["#008080", "#00B3B3", "#00E6E6", "#1AFFFF", "#4DFFFF"],
  },
  {
    name: "Crimson",
    mainColor: "#DC143C",
    shades: ["#6E0A1E", "#9A0E2A", "#C61236", "#E02C50", "#E75B77"],
  },
];

export const clothingData = [
  {
    type: "Shirt",
    subtype: "T-shirt",
    sleeve: "Sleeveless",
    fabric: "Synthetic",
    cut: "Zip-up",
    waist: "Low rise",
    pattern: "Solid",
    neck: "Turtleneck",
    colors: ["#800080", "#8D1A1A", "#A64D4D", "#1AFF1A", "#730000"],
  },
  {
    type: "Layer",
    subtype: "Sweatshirt",
    sleeve: "Long-sleeve",
    fabric: "Cork",
    cut: "Fitted",
    waist: "Mid rise",
    pattern: "Horizontal stripes",
    neck: "Collared",
    colors: ["#FFD700", "#B3868E", "#440075", "#808000", "#FFC6D0"],
  },
  {
    type: "Shirt",
    subtype: "T-shirt",
    sleeve: "Long-sleeve",
    fabric: "Woven",
    cut: "Loose",
    waist: "Low rise",
    pattern: "Geometric print",
    neck: "Collared",
    colors: ["#0000FF", "#6E0A1E", "#0000B3", "#0000B3", "#737373"],
  },
  {
    type: "Trouser",
    subtype: "Sweatpants",
    sleeve: "Long-sleeve",
    fabric: "Chiffon",
    cut: "Flare",
    waist: "Mid rise",
    pattern: "Graphic tee",
    neck: "Boat neck",
    colors: ["#808080", "#A15D1A", "#FFDB1A", "#A1A1AF", "#6400B3"],
  },
  {
    type: "Layer",
    subtype: "Jacket",
    sleeve: "Long-sleeve",
    fabric: "Chambray",
    cut: "Zip-up",
    waist: "High waisted",
    pattern: "Graphic tee",
    neck: "V-neck",
    colors: ["#8F00FF", "#400040", "#40806A", "#1AFF1A", "#1A1AFF"],
  },
  {
    type: "Footwear",
    subtype: "Oxfords",
    sleeve: "Long-sleeve",
    fabric: "Woven",
    cut: "High-top",
    waist: "Mid rise",
    pattern: "Horizontal stripes",
    neck: "Boat neck",
    colors: ["#800080", "#400040", "#400040", "#804028", "#805300"],
  },
  {
    type: "Shirt",
    subtype: "T-shirt",
    sleeve: "Long-sleeve",
    fabric: "Denim",
    cut: "Straight",
    waist: "Mid rise",
    pattern: "Floral",
    neck: "Turtleneck",
    colors: ["#000000", "#FF1A1A", "#730073", "#7B7B6E", "#0000B3"],
  },
  {
    type: "Layer",
    subtype: "Sweater",
    sleeve: "Sleeveless",
    fabric: "Chino",
    cut: "Camisole",
    waist: "Low rise",
    pattern: "Geometric print",
    neck: "Crew neck",
    colors: ["#DC143C", "#FFC6D0", "#00E600", "#FFFF1A", "#FFD3DB"],
  },
  {
    type: "Layer",
    subtype: "Hoodie",
    sleeve: "Short-sleeve",
    fabric: "Suede",
    cut: "Zip-up",
    waist: "Mid rise",
    pattern: "Plaid",
    neck: "Collared",
    colors: ["#FF00FF", "#4DFF4D", "#00E6E6", "#400040", "#E6E600"],
  },
  {
    type: "Footwear",
    subtype: "Sneakers",
    sleeve: "Short-sleeve",
    fabric: "Chiffon",
    cut: "Wedge",
    waist: "Low rise",
    pattern: "Graphic tee",
    neck: "Boat neck",
    colors: ["#00FFFF", "#7B7B6E", "#FFFF4D", "#800080", "#0000B3"],
  },
  {
    type: "Shirt",
    subtype: "Polo shirt",
    sleeve: "Short-sleeve",
    fabric: "Chambray",
    cut: "Zip-up",
    waist: "Mid rise",
    pattern: "Solid",
    neck: "Collared",
    colors: ["#F5F5DC", "#FF4D4D", "#B14DFF", "#6E0A1E", "#E6ADB7"],
  },
  {
    type: "Shirt",
    subtype: "T-shirt",
    sleeve: "Sleeveless",
    fabric: "Knit",
    cut: "Zip-up",
    waist: "High waisted",
    pattern: "Floral",
    neck: "Boat neck",
    colors: ["#E6E6FA", "#FFC04D", "#B30000", "#E67248", "#E67248"],
  },
  {
    type: "Trouser",
    subtype: "Shorts",
    sleeve: "Short-sleeve",
    fabric: "Quilted",
    cut: "Flare",
    waist: "Low rise",
    pattern: "Solid",
    neck: "Turtleneck",
    colors: ["#F5F5DC", "#B3868E", "#E6E600", "#4DFF4D", "#800000"],
  },
  {
    type: "Shirt",
    subtype: "Button-up",
    sleeve: "Long-sleeve",
    fabric: "Knit",
    cut: "Loose",
    waist: "Low rise",
    pattern: "Horizontal stripes",
    neck: "Crew neck",
    colors: ["#4B0082", "#E67248", "#008000", "#805300", "#B300B3"],
  },
  {
    type: "Footwear",
    subtype: "Sneakers",
    sleeve: "Long-sleeve",
    fabric: "Synthetic",
    cut: "Wedge",
    waist: "Low rise",
    pattern: "Checked",
    neck: "Collared",
    colors: ["#964B00", "#EEEEFC", "#1AFFFF", "#A64DA6", "#FFAE1A"],
  },
  {
    type: "Trouser",
    subtype: "Sweatpants",
    sleeve: "Short-sleeve",
    fabric: "Leather",
    cut: "Loose",
    waist: "Mid rise",
    pattern: "Vertical stripes",
    neck: "Crew neck",
    colors: ["#800080", "#8D1A1A", "#F6F6E0", "#F6F6E0", "#5A005A"],
  },
  {
    type: "Shirt",
    subtype: "T-shirt",
    sleeve: "Long-sleeve",
    fabric: "Denim",
    cut: "Camisole",
    waist: "Mid rise",
    pattern: "Graphic tee",
    neck: "Crew neck",
    colors: ["#E6E6FA", "#800080", "#9A1AFF", "#FFC04D", "#E60000"],
  },
  {
    type: "Layer",
    subtype: "Jacket",
    sleeve: "Sleeveless",
    fabric: "Leather",
    cut: "Zip-up",
    waist: "Low rise",
    pattern: "Vertical stripes",
    neck: "Crew neck",
    colors: ["#000000", "#1AFF1A", "#400000", "#800080", "#B300B3"],
  },
  {
    type: "Trouser",
    subtype: "Chinos",
    sleeve: "Short-sleeve",
    fabric: "Quilted",
    cut: "Slim",
    waist: "High waisted",
    pattern: "Checked",
    neck: "Collared",
    colors: ["#00FFFF", "#805300", "#5A005A", "#440075", "#9A1AFF"],
  },
  {
    type: "Layer",
    subtype: "Sweater",
    sleeve: "Short-sleeve",
    fabric: "Chino",
    cut: "Zip-up",
    waist: "High waisted",
    pattern: "Floral",
    neck: "V-neck",
    colors: ["#7FFFD4", "#806C00", "#400040", "#E600E6", "#874400"],
  },
  {
    type: "Layer",
    subtype: "Hoodie",
    sleeve: "Short-sleeve",
    fabric: "Denim",
    cut: "Camisole",
    waist: "High waisted",
    pattern: "Vertical stripes",
    neck: "Turtleneck",
    colors: ["#800000", "#FF4D4D", "#1A1AFF", "#6400B3", "#480080"],
  },
  {
    type: "Layer",
    subtype: "Jacket",
    sleeve: "Long-sleeve",
    fabric: "Chino",
    cut: "Camisole",
    waist: "Low rise",
    pattern: "Horizontal stripes",
    neck: "Crew neck",
    colors: ["#F5F5DC", "#40806A", "#B300B3", "#A64DA6", "#B37300"],
  },
  {
    type: "Layer",
    subtype: "Jacket",
    sleeve: "Short-sleeve",
    fabric: "Synthetic",
    cut: "Camisole",
    waist: "High waisted",
    pattern: "Plaid",
    neck: "Crew neck",
    colors: ["#FFFFFF", "#FF8C62", "#874400", "#FFE34D", "#CFCFE1"],
  },
  {
    type: "Trouser",
    subtype: "Sweatpants",
    sleeve: "Sleeveless",
    fabric: "Quilted",
    cut: "Fitted",
    waist: "Low rise",
    pattern: "Color block",
    neck: "Turtleneck",
    colors: ["#7FFFD4", "#9A0E2A", "#B14DFF", "#A6A6A6", "#CFCFE1"],
  },
  {
    type: "Trouser",
    subtype: "Shorts",
    sleeve: "Sleeveless",
    fabric: "Wool",
    cut: "Flare",
    waist: "High waisted",
    pattern: "Animal print",
    neck: "Boat neck",
    colors: ["#DC143C", "#FFDB1A", "#00B3B3", "#A64DA6", "#E6C200"],
  },
  {
    type: "Trouser",
    subtype: "Shorts",
    sleeve: "Sleeveless",
    fabric: "Cotton",
    cut: "Flare",
    waist: "Low rise",
    pattern: "Vertical stripes",
    neck: "Turtleneck",
    colors: ["#DC143C", "#814DA8", "#0000E6", "#E6C200", "#E69500"],
  },
  {
    type: "Shirt",
    subtype: "Polo shirt",
    sleeve: "Sleeveless",
    fabric: "Silk",
    cut: "Straight",
    waist: "High waisted",
    pattern: "Plaid",
    neck: "Crew neck",
    colors: ["#00FFFF", "#9A1AFF", "#6E0A1E", "#FF4DFF", "#F6F6E0"],
  },
  {
    type: "Layer",
    subtype: "Hoodie",
    sleeve: "Sleeveless",
    fabric: "Chino",
    cut: "Fitted",
    waist: "Mid rise",
    pattern: "Animal print",
    neck: "Turtleneck",
    colors: ["#F5F5DC", "#400000", "#5A0000", "#693500", "#A64D4D"],
  },
  {
    type: "Trouser",
    subtype: "Jeans",
    sleeve: "Long-sleeve",
    fabric: "Chino",
    cut: "Straight",
    waist: "Mid rise",
    pattern: "Solid",
    neck: "Crew neck",
    colors: ["#00FF00", "#FFDB1A", "#FFDB1A", "#ACAC9A", "#806066"],
  },
  {
    type: "Shirt",
    subtype: "Button-up",
    sleeve: "Long-sleeve",
    fabric: "Synthetic",
    cut: "Loose",
    waist: "Mid rise",
    pattern: "Horizontal stripes",
    neck: "Collared",
    colors: ["#964B00", "#400040", "#1AFF1A", "#40806A", "#730073"],
  },
  {
    type: "Trouser",
    subtype: "Jeans",
    sleeve: "Short-sleeve",
    fabric: "Leather",
    cut: "Slim",
    waist: "Low rise",
    pattern: "Color block",
    neck: "Turtleneck",
    colors: ["#FF7F50", "#737373", "#59B394", "#7B7B6E", "#00E6E6"],
  },
  {
    type: "Trouser",
    subtype: "Sweatpants",
    sleeve: "Short-sleeve",
    fabric: "Synthetic",
    cut: "Fitted",
    waist: "Low rise",
    pattern: "Graphic tee",
    neck: "Turtleneck",
    colors: ["#4B0082", "#DDDDC6", "#72E6BF", "#B3B300", "#E6C200"],
  },
  {
    type: "Layer",
    subtype: "Blazer",
    sleeve: "Sleeveless",
    fabric: "Wool",
    cut: "Fitted",
    waist: "High waisted",
    pattern: "Graphic tee",
    neck: "Crew neck",
    colors: ["#808080", "#000080", "#730000", "#806066", "#E02C50"],
  },
  {
    type: "Shirt",
    subtype: "Polo shirt",
    sleeve: "Short-sleeve",
    fabric: "Knit",
    cut: "Loose",
    waist: "High waisted",
    pattern: "Vertical stripes",
    neck: "Turtleneck",
    colors: ["#FF7F50", "#1AFF1A", "#6E0A1E", "#A15D1A", "#404040"],
  },
  {
    type: "Footwear",
    subtype: "Sandals",
    sleeve: "Short-sleeve",
    fabric: "Suede",
    cut: "High-top",
    waist: "High waisted",
    pattern: "Color block",
    neck: "Collared",
    colors: ["#FFFFFF", "#E6ADB7", "#E6C200", "#F6F6E0", "#E600E6"],
  },
  {
    type: "Shirt",
    subtype: "Button-up",
    sleeve: "Long-sleeve",
    fabric: "Flannel",
    cut: "Zip-up",
    waist: "Mid rise",
    pattern: "Floral",
    neck: "Collared",
    colors: ["#FFC0CB", "#B6814D", "#1AFF1A", "#E69500", "#5D1A8F"],
  },
  {
    type: "Trouser",
    subtype: "Chinos",
    sleeve: "Short-sleeve",
    fabric: "Cork",
    cut: "Fitted",
    waist: "Mid rise",
    pattern: "Animal print",
    neck: "V-neck",
    colors: ["#800080", "#E6ADB7", "#806066", "#9A0E2A", "#FFFF1A"],
  },
  {
    type: "Trouser",
    subtype: "Sweatpants",
    sleeve: "Short-sleeve",
    fabric: "Knit",
    cut: "Fitted",
    waist: "Mid rise",
    pattern: "Horizontal stripes",
    neck: "V-neck",
    colors: ["#FF7F50", "#0000E6", "#EEEEFC", "#4B2600", "#404040"],
  },
  {
    type: "Footwear",
    subtype: "Sandals",
    sleeve: "Long-sleeve",
    fabric: "Denim",
    cut: "High-top",
    waist: "High waisted",
    pattern: "Animal print",
    neck: "Crew neck",
    colors: ["#0000FF", "#5A5A5A", "#814DA8", "#440075", "#E69500"],
  },
  {
    type: "Shirt",
    subtype: "T-shirt",
    sleeve: "Short-sleeve",
    fabric: "Silk",
    cut: "Loose",
    waist: "High waisted",
    pattern: "Graphic tee",
    neck: "V-neck",
    colors: ["#0000FF", "#FF8C62", "#5A005A", "#E69500", "#8D1A8D"],
  },
  {
    type: "Layer",
    subtype: "Sweater",
    sleeve: "Long-sleeve",
    fabric: "Flannel",
    cut: "Zip-up",
    waist: "High waisted",
    pattern: "Floral",
    neck: "Turtleneck",
    colors: ["#800080", "#B35938", "#814DA8", "#4B2600", "#ACAC9A"],
  },
  {
    type: "Footwear",
    subtype: "Sandals",
    sleeve: "Sleeveless",
    fabric: "Cotton",
    cut: "High-top",
    waist: "Low rise",
    pattern: "Floral",
    neck: "V-neck",
    colors: ["#FF00FF", "#737373", "#008000", "#E9E9FB", "#FFC04D"],
  },
  {
    type: "Trouser",
    subtype: "Regular trousers",
    sleeve: "Sleeveless",
    fabric: "Cotton",
    cut: "Flare",
    waist: "Mid rise",
    pattern: "Geometric print",
    neck: "Boat neck",
    colors: ["#00FFFF", "#806C00", "#9A0E2A", "#A64D4D", "#E67248"],
  },
  {
    type: "Footwear",
    subtype: "Oxfords",
    sleeve: "Sleeveless",
    fabric: "Chino",
    cut: "Mules",
    waist: "Mid rise",
    pattern: "Geometric print",
    neck: "Crew neck",
    colors: ["#FFC0CB", "#1AFFFF", "#9A1AFF", "#808000", "#8D1A1A"],
  },
  {
    type: "Footwear",
    subtype: "Sneakers",
    sleeve: "Long-sleeve",
    fabric: "Suede",
    cut: "Slip on",
    waist: "Low rise",
    pattern: "Animal print",
    neck: "V-neck",
    colors: ["#808080", "#B3868E", "#1AFFFF", "#73737D", "#E6E600"],
  },
  {
    type: "Layer",
    subtype: "Blazer",
    sleeve: "Long-sleeve",
    fabric: "Chiffon",
    cut: "Fitted",
    waist: "High waisted",
    pattern: "Vertical stripes",
    neck: "Crew neck",
    colors: ["#FF7F50", "#4D4DFF", "#B39700", "#FFA585", "#59B394"],
  },
  {
    type: "Layer",
    subtype: "Hoodie",
    sleeve: "Sleeveless",
    fabric: "Suede",
    cut: "Zip-up",
    waist: "Mid rise",
    pattern: "Solid",
    neck: "Boat neck",
    colors: ["#FF0000", "#B3868E", "#E75B77", "#E9E9FB", "#00B300"],
  },
  {
    type: "Footwear",
    subtype: "Oxfords",
    waist: "Mid rise",
    sleeve: "Long-sleeve",
    fabric: "Lace",
    cut: "Straight",
    pattern: "Color block",
    neck: "V-neck",
    colors: ["#7FFFD4", "#B30000", "#FFFF1A", "#9A1AFF", "#4DFF4D"],
  },
];
