import { StatusBar, StyleSheet } from "react-native";
import { COLORS, FONTS } from "./general";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    fontFamily: FONTS.regular,
    padding: 12,
    marginTop: StatusBar.currentHeight,
    gap: 15,
    backgroundColor: COLORS.black,
  },
  header: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  leftHeader: { flex: 1, gap: 2 },
  welcomeText: {
    fontFamily: FONTS.regular,
    fontSize: 18,
    color: COLORS.white,
  },
  nameText: {
    color: COLORS.white,
    fontFamily: FONTS.medium,
    fontSize: 20,
  },
  profileImage: { width: 35, height: 35 },
  creditContainer: {
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  credits: { flex: 1, gap: 2 },
  creditAmount: {
    fontFamily: FONTS.medium,
    color: COLORS.white,
    fontSize: 30,
  },
  creditText: { fontFamily: FONTS.regular, color: COLORS.white, fontSize: 16 },
  buyCredits: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  buyCreditsText: { fontSize: 18, fontFamily: FONTS.regular, color: "white" },
  closetView: {
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    width: "100%",
    gap: 10,
  },
  itemsText: {
    fontFamily: FONTS.medium,
    fontSize: 23,
    marginRight: "auto",
    color: COLORS.white,
  },
  closetContainer: {
    flexDirection: "column",
    alignItems: "center",
    gap: 20,
    justifyContent: "center",
  },
  noItemsView: {
    height: 300,
    zIndex: -15,
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
  },
  noItemsText: { fontFamily: FONTS.regular, fontSize: 18, color: COLORS.white },
  suggestions: {
    backgroundColor: COLORS.green,
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  suggestionsText: { fontSize: 18, fontFamily: FONTS.regular, color: "white" },
  addStuff: { backgroundColor: COLORS.green, borderRadius: 8, padding: 10 },
  addStuffText: { fontSize: 18, fontFamily: FONTS.regular, color: "white" },
  itemsView: { width: "100%", marginBottom: 160 },
  itemView: {
    // borderWidth: 1,
    borderColor: COLORS.white,
    padding: 6,
    backgroundColor: COLORS.primary,
    gap: 10,
    borderRadius: 10,
    marginRight: 10,
    display: "flex",
    justifyContent: "space-between",
  },
  itemTop: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexDirection: "row",
  },
  imageView: {
    width: 70,
    height: 55,
    backgroundColor: "white",
    padding: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
  },
  itemImage: { width: 40, height: 40 },
  colorView: {
    width: 87,
    height: 55,
    flexDirection: "row",
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    overflow: "hidden",
    gap: 6,
    display: "flex",
    justifyContent: "flex-start",
    flexWrap: "wrap",
  },
  colorStyle: { width: 25, height: 25, borderRadius: 5 },
  typeText: { fontFamily: FONTS.medium, fontSize: 18, color: COLORS.white },
  scrollItemView: { gap: 8, marginBottom: 15 },
  scrollView: { gap: 4 },
  scrollItemText: {
    fontFamily: FONTS.medium,
    fontSize: 20,
    color: COLORS.white,
  },
});
